### ISSUE TITLE
[BUG] EU-Mode Reactor Voltage

### ISSUE THREAD

**Issue by GManClone** [Su5eD/IC2-Patcher#1] opened 2021-06-19 16:43 UTC
**Describe the bug**
It seems that the output voltage of the EU reactor has been set to Insane Voltage (8192 EU), which causes any blocks not behind an EV (8192 -> 2048) transformer to blow up,  even if the EU reactor only generates 5 EU/t. 

**To Reproduce**
1. Install IC2x 1.12.2,  version 221
2. Install IC2 Patcher, version 1.0-beta 2
3. Setup an EU reactor with a single uranium rod (and cooling)
4. Connect the reactor to a MFSU directly or using wires.
5. Turn the reactor on.
6. Now try the same setup,  but put an EV transformer between the reactor and the MFSU.

**Expected behavior**
Without IC2 Patcher,  I can easily connect any block or MFSU to a reactor, as long as the output EU packet is within the voltage limit of the machine or storage block.  

**Additional context**
I did not alter any energy balance configs. 
I also checked the console for any error messages (or crashes). Nothing shows up.
What's also strange is that wires don't burn up as long as the output packets are below their voltage rating (so tin won't burn up by a 5 EU/t reactor). But the target block (MFSU) does blow up. 
If I connect a MFSU to another MFSU (or using HV/glass cables), all works as expected (no explosions/burning cables).   So it seems that ONLY the reactor has been affected.
Additionally,  I added Nuclearcraft and connected a lithium ion advanced battery block,  DU and elite variants as well.  The advanced battery block is set to IC2 tier 4, DU tier 5 and elite tier 6. Only the advanced lithium ion battery blew up,  the higher tiers accepted power from the reactor directly without blowing up.  This confirms my suspicions that the reactor seemingly outputs at IV, regardless of its actual power output. 

[Also video proof of the (unintentional) bug.](https://i.gyazo.com/a0aee8c6bb2402f40e3028643e26570a.mp4)

**Comment by Su5eD** [comment] 2021-06-19 19:39
This is caused by my patch to EnergyCalculatorLeg, which makes it compare the tiers of the source and target instead of the transferred energy to calculate whether the machine should explode.

The reactor is hardcoded to source tier 5, that's why it explodes the MFSU with this patch.

I can see 2 possible solutions here:
1) Disable the patch
2) Patch the reactor to dynamically determine its source tier depending on the current output voltage. Other generators might need such a fix, too.

**Comment by GManClone** [comment] 2021-06-19 19:55
When you try solution #2, that might break EU generators from other addons as well.

**Comment by Su5eD** [comment] 2021-06-20 08:30
Yeah, I forgot about that. Disabling the patch will be the best solution then.

**Closed** 2021-06-20 19:01 UTC
Labels: bug
